backend:
  name: github
  repo: capsia37/community.ubuntu-touch.io
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content"
    create: true
    nested:
      depth: 30
      summary: "{{ title }}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Excerpt"
        name: "excerpt"
        widget: "string"
      - label: "Icon"
        name: "icon"
        widget: "file"
        required: false
        allow_multiple: false
        media_library:
          config:
            multiple: false
      - label: Article
        name: body
        widget: markdown
      - label: "External Links"
        name: "externalLinks"
        widget: "object"
        fields:
          - label: "Resources"
            name: "resources"
            widget: "list"
            fields:
              - label: "Link label"
                name: "text"
                widget: "string"
              - label: "Link destination"
                name: "target"
                widget: "string"
              - label: "Link category"
                name: "category"
                widget: "select"
                options: ["Blog", "Audiocast", "Youtube"]
          - label: "Media"
            name: "media"
            widget: "list"
            fields:
              - label: "Link label"
                name: "text"
                widget: "string"
              - label: "Link destination"
                name: "target"
                widget: "string"
              - label: "Link category"
                name: "category"
                widget: "select"
                options: ["Blog", "Audiocast", "Youtube"]
          - label: "People"
            name: "people"
            widget: "list"
            fields:
              - label: "Name or nickname"
                name: "text"
                widget: "string"
              - label: "Link destination"
                name: "target"
                widget: "string"
          - label: "Discussions"
            name: "join"
            widget: "list"
            fields:
              - label: "Link label"
                name: "text"
                widget: "string"
              - label: "Link destination"
                name: "target"
                widget: "string"
              - label: "Link category"
                name: "icon"
                widget: "select"
                options: ["yumi", "telegram", "irc"]
      - label: "Faq"
        name: "faq"
        widget: "list"
        fields:
          - label: "Question"
            name: "question"
            widget: "string"
          - label: "Answer"
            name: "content"
            widget: "string"
      - label: "Advanced options"
        name: "options"
        widget: "object"
        fields:
          - label: "Layout"
            name: "layout"
            widget: "select"
            options: ["article", "categories"]
            default: ["article"]
          - label: "Hide breadcrumb"
            name: "hideBreadcrumb"
            widget: "boolean"
          - label: "Hide sidebar"
            name: "hideSidebar"
            widget: "boolean"
          - label: "Show image in header"
            name: "showHeaderImage"
            widget: "boolean"
