backend:
  name: github
  repo: capsia37/community.ubuntu-touch.io
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content"
    create: true
    nested:
      depth: 30
      summary: "{{ title }}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Excerpt"
        name: "excerpt"
        widget: "string"
      - label: "Icon"
        name: "icon"
        widget: "file"
        required: false
        allow_multiple: false
        media_library:
          config:
            multiple: false
      - label: Article
        name: body
        widget: markdown
